### ISSUE TITLE
Robotlegs "Toolbox" for tracking resources/addons/etc

### ISSUE THREAD

**Issue by joelhooks** [robotlegs/robotlegs.github.com#3]
http://toolbox.no.de is so awesome. RL needs a resource tracker of some sort. It'd be double sweet if it was hooked into Github and automated in some form or fashion.

**Comment by Ondina** [comment]
I couldn't agree more!

**Comment by joelhooks** [comment]
https://github.com/activesphere/nodetoolbox - they share how to make it happen anyway. I'd wager that NPM is the reason they can pull this off.

**Comment by creynders** [comment]
That's something I definitely missed on the v1 site, an easy way to find extensions etc. @Ondina did a great job trying to maintain that one thread, but it wasn't very efficient nor clear of course. Some kind of centralizing site or site section for all RL resources is really a must I think. And it'd be great to have some kind of "officially" approved extensions distinction made or some kind of ordering of the extension list by num of downloads or votes or so. 
Take the drupal site for instance, it's great that you can find a few thousand modules, but the flaw is that it's hard to distinguish the really robust, used-by-the-pros, must-have modules and the can't-seem-to-find-some-functionality-there-i-fixed-it modules.

**Comment by Ondina** [comment]
@creynders I agree with you on the fact that that thread isn’t efficient, since it’s not an interactive app. 
But, all examples, tutorials, utilities etc are at least kind of centralized.
I listed them in alphabetical order because I didn’t want to be the (only) one deciding which links met criteria like  “really robust, used-by-the-pros, must-have “. On the one hand, it wouldn’t have been fair to impose my subjective criteria, and on the other hand it would have required a lot of time to review every article, tutorial, demo..

I also agree on the benefits of having "officially" approved extensions and a voting system or something like that. In fact, that was something I’ve already suggested:
http://knowledge.robotlegs.org/discussions/suggestions/39-utilities-overview#comment_3302463

So, I'm all for finding an efficient solution :) 
Let’s see what options we have.
http://toolbox.no.de/  ?

**Comment by creynders** [comment]
In fact (probably not the right thread, but since I brought it up here) talking about drupal: why not use drupal for the RL2 site? It can be easily set up to have everything that's been brought up as a suggestion. Forum, resource submissions, votings, etc. etc.

@Ondina as I said, you did a great job, but it's simply not maintainable.

**Comment by Ondina** [comment]
looking at Sites Made with Drupal: http://drupal.org/cases

**Comment by Ondina** [comment]
I’m sure Shaun, Till, Stray and Joel won’t have enough time to take care of this aspect of the framework in all its details, at least for as long as rl2 is still a baby ;)
I think the forum + resources + website design +etc should be a community effort, as Joel mentioned here https://github.com/robotlegs/robotlegs.github.com/issues/5 referring to the visual design.
A single person can't do it (all of the above mentioned) alone on the long term. 
In my opinion involving more people from the community would be a good idea. If you (all) agree on that, we should put it up for discussion on the rl forum or google group, where the participation rate is higher than on github.

@creynders - drupal looks good. And I agree that having a single entry point to everything related to the framework would be ideal. Having github for code and something like drupal for everything else would be the second best option.

**Comment by creynders** [comment]
I'll be glad to help with setting up and maintaining the site, if it's done in drupal. I don't know any of the other cms frameworks really...

**Comment by Ondina** [comment]
@creynders great!

**Comment by darscan** [comment]
@creynders Awesome! I have a VPS we can install Drupal on if you want to start playing around. Same box that hosts robotlegs.org

**Comment by creynders** [comment]
Great! I'll send you a mail.
